const menu = [
  {
    id: 1,
    title: '泰北香拌松阪豬',
    category: 'salad',
    price: 380,
    img: './images/songbangsalad.jpg',
    desc: `鮮嫩松阪豬肉片搭配鮮脆的小黃瓜與紫洋蔥絲， 拌以主廚特調泰北涼拌醬汁，鮮美過癮、清爽開胃！ `,
  },
  {
    id: 2,
    title: '海鮮什蔬沙律',
    category: 'salad',
    price: 350,
    img: './images/seafoodsalad.jpg',
    desc: `中卷、蝦仁等鮮美好料與清脆什蔬涼拌，辛辣又爽口，再來杯啤酒更是痛快過癮！ `,
  },
  {
    id: 3,
    title: '鮮蔬沙律',
    category: 'salad',
    price: 160,
    img: './images/vegsalad.jpg',
    desc: `多種新鮮蔬菜，拌入特製涼拌醬，富含多種維生素，是健康又營養的選擇。`,
  },
  {
    id: 4,
    title: '冬粉鮮蝦煲',
    category: 'SEAFOOD',
    price: 480,
    img: './images/wintersh.jpg',
    desc: `精選十隻鮮海蝦，肉質極為甜脆甘美，與冬粉文火細熬煲煮，鮮美得令人垂涎三尺。`,
  },
  {
    id: 5,
    title: '泰味鳳梨蝦球',
    category: 'SEAFOOD',
    price: 300,
    img: './images/shball.jpg',
    desc: `酥脆鮮嫩蝦仁，佐以新鮮鳳梨丁，加入獨特爽口的沙拉醬拌製而成，連小朋友都愛吃喔！`,
  },
  {
    id: 6,
    title: '檸檬清蒸魚',
    category: 'SEAFOOD',
    price: 480,
    img: './images/lemonfish.jpg',
    desc: `清蒸新鮮鱸魚，淋上檸檬汁、蒜蓉、辣椒、香菜的獨門醬汁，酸辣的帶勁口感，令人捨不得放下筷子`,
  },
  {
    id: 7,
    title: '鐵板香辣海鮮',
    category: 'SEAFOOD',
    price: 350,
    img: './images/ironseafood.jpg',
    desc: `蝦仁、中卷、蛤蜊等新鮮海鮮，搭配青蔬以鐵板滋滋燒炒，色、香、味的豐富呈現！`,
  },
  {
    id: 8,
    title: '湄南跳魚',
    category: 'SEAFOOD',
    price: 480,
    img: './images/jumpfish.jpg',
    desc: `新鮮鱸魚炸得表皮酥黃、肉質鮮嫩，現場澆上特熬的香濃醬汁、滋滋作響，入口難忘。`,
  },
  {
    id: 9,
    title: '摩摩喳喳 (冰/熱)',
    category: 'DESSERTS',
    price: 95,
    img: './images/momocha.jpg',
    desc: `西米露、綠豆沙、亞達枳、菠蘿蜜、紅毛丹、石榴紅寶石等豐富材料， 淋上香氣出眾的七葉蘭糖汁及椰奶，瓦城超人氣招牌甜點。`,
  },
  {
    id: 10,
    title: '小清新檸檬冰',
    category: 'DESSERTS',
    price: 95,
    img: './images/lemonice.jpg',
    desc: `酸甜檸檬冰沙搭配七葉蘭糖水的清香，妝點著石榴紅寶石， 用味蕾感受著小清新。`,
  },
  {
    id: 11,
    title: '椰漿西米露 (冰/熱)',
    category: 'DESSERTS',
    price: 90,
    img: './images/westrice.jpg',
    desc: `QQ西米露搭配芋頭，淋上椰奶，最有南洋風味。`,
  },
  {
    id: 12,
    title: '什錦水果冰',
    category: 'DESSERTS',
    price: 90,
    img: './images/fruitIce.jpg',
    desc: `菠蘿蜜、亞達枳、紅毛丹三種泰國盛產水果，享受熱帶風情。`,
  },
  {
    id: 13,
    title: '椰香石榴冰',
    category: 'DESSERTS',
    price: 90,
    img: './images/stone.jpg',
    desc: `特製石榴紅寶石，外Q內脆，搭配亞達枳，冰甜滑順一口接一口。`,
  },
   {
    id: 14,
    title: '辣炒豬肉',
    category: 'meat',
    price: 280,
    img: './images/pork.jpg',
    desc: `豬絞肉與泰國辣椒、小番茄、九層塔熱炒，辣味十足。`,
  },
   {
    id: 15,
    title: 'BBQ嫩烤松阪豬',
    category: 'meat',
    price: 395,
    img: './images/songbangpig.jpg',
    desc: `頂級厚切松阪豬肉，嫩中帶脆、鮮甜爽口的獨特口感，再搭配烤鳳梨片與兩種自製沾醬，一吃愛上！`,
  },
   {
    id: 16,
    title: '泰式咖哩雞',
    category: 'meat',
    price: 300,
    img: './images/Tailand curry.jpg',
    desc: `大塊雞腿肉以泰國黃咖哩熬煮入味，口感溫潤香濃，再來塊鬆軟的馬鈴薯，飽實感十足！`,
  },
   {
    id: 17,
    title: '綠咖哩椰汁雞',
    category: 'meat',
    price: 280,
    img: './images/Curry.jpg',
    desc: `鮮嫩雞腿肉片，加上長豆、九層塔及進口綠咖哩烹調而成，配飯香濃開胃！`,
  },
   {
    id: 18,
    title: '風味椒麻雞',
    category: 'meat',
    price: 300,
    img: './images/JiuMaji.jpg',
    desc: `將整隻雞腿沾粉酥炸，外層香酥，肉質鮮嫩，再淋上我們獨特的椒麻醬汁真的非常好吃！`,
  },
];
export default menu;
